### ISSUE TITLE
DeathLink

### ISSUE THREAD

**Issue by Ijwu** [Ijwu/Archipelago.HollowKnight#19]
Implement DeathLink.

It should not eat your Geo if you die once and then get killed by DeathLink. If you already have a shade in the world then DeathLink should transfer all Geo from that shade to the new one.

**Comment by dewiniaid** [comment]
I had some thoughts on this:

Deathlink shouldn't be a way to teleport your shade to a more convenient location.  Nor should it be possible to permanently lose geo without legitimate deaths.

The idea I had is:

- If you die normally, all normal shade mechanics apply -- geo loss, shade spawn, etc.
- If you die due to Deathlink and all of the below are true, it is processed as a normal death:
  - A shade does not already exist
  - A shade spawn exists in the current scene.  (This excludes shops)
  - The scene is not the lifeblood core room (Shades in that room spawn OOB and are unrecoverable; this is a Vanilla bug)
- Otherwise, no shade is spawned and no geo is lost.
